name: Build master

on:
  push:
    branches:
      - main
      - test-cicd
  workflow_dispatch:

jobs:
  release:
    name: build docs
    runs-on: ubuntu-latest

    steps:
      # æ£€å‡º Git ä»“åº“
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      # å®‰è£… Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      # å®‰è£… MkDocs + æ’ä»¶
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin
      # æ„å»º MkDocs
      - name: Build
        run: |
          mkdocs build

      # éƒ¨ç½²åˆ°æœåŠ¡å™¨
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: ./site/
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_BEFORE: |
            echo "ğŸ”§ å¼€å§‹éƒ¨ç½²..."
            echo "æ—¶é—´: $(date)"
          SCRIPT_AFTER: |
            echo "âœ… éƒ¨ç½²å®Œæˆ"
            echo "æ—¶é—´: $(date)"